apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: monica-ns   # must match the namespace in deployment.yaml
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
